### PR TITLE
HP-895: package updates

### PR DESCRIPTION
**Pull request by NikoHelle**
Updated react-scripts and apollo client, because of vulnerabilities reported by Snyk.

Updated also typescript and removed useless jest-environment-jsdom-sixteen.

### CODE REVIEW

**Comment by NikoHelle** [comment]
Made a new commit to this PR which cleans the yarn.lock a bit. The updated lock file required quite a lot of other changes.

**Comment by akikoskinen** [comment]
> Made a new commit to this PR which cleans the yarn.lock a bit. The updated lock file required quite a lot of other changes.

That last commit now does quite a many things, which is evident from the commit message. Perhaps this whole PR could be reorganized a bit. The first commit could clean the `yarn.lock` file and do other necessary changes caused by that. Then a second commit would update react-scripts, the next commit updates typescript etc., all of these keeping the `yarn.lock` clean all the time.

**Comment by NikoHelle** [comment]
I made a new branch and PR which have same changes: https://github.com/City-of-Helsinki/example-ui-profile/pull/35

Easier than moving commits before commits that affected the latter ones.

I'll close this one later.

**Comment by NikoHelle** [comment]
Closed because of https://github.com/City-of-Helsinki/example-ui-profile/pull/35

**Pull request closed without merging**
